name: Build and Release Stockfish 18

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04, windows-2022, macos-13]
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install -y build-essential clang

      - name: Install dependencies (Windows)
        if: runner.os == 'Windows'
        run: |
          choco install make

      - name: Build Stockfish
        run: |
          cd src
          make -j$(nproc) build ARCH=x86-64-modern
        shell: bash

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: stockfish-${{ runner.os }}
          path: src/stockfish*

  release:
    needs: build
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: "stockfish-*/*"
          tag_name: ${{ github.ref_name }}
          name: Stockfish ${{ github.ref_name }}
          draft: false
          prerelease: false
          fail_on_unmatched_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
