name: Build KhanhFish

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies (Linux/macOS)
        if: runner.os != 'Windows'
        run: sudo apt-get update && sudo apt-get install -y make g++

      - name: Install dependencies (Windows)
        if: runner.os == 'Windows'
        run: |
          choco install make mingw

      - name: Build KhanhFish (Linux/macOS)
        if: runner.os != 'Windows'
        run: |
          cd src
          make -j$(nproc) build ARCH=x86-64

      - name: Build KhanhFish (Windows)
        if: runner.os == 'Windows'
        run: |
          cd src
          make -j4 build ARCH=x86-64

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: khanhfish-${{ runner.os }}
          path: src/khanhfish

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/**
          tag_name: latest
          name: KhanhFish Latest Release
          body: "Latest build of KhanhFish engine."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
