name: Build Stockfish Dev on Windows

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'  # Build tự động mỗi ngày

jobs:
  build:
    runs-on: windows-latest  # Chạy trên Windows
    permissions:
      contents: read
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          choco install make mingw -y
        shell: powershell

      - name: Compile Stockfish
        run: |
          cd src
          make build ARCH=x86-64
          move stockfish.exe ..\stockfish-dev.exe
        shell: cmd

      - name: Upload compiled binary
        uses: actions/upload-artifact@v3
        with:
          name: stockfish-dev-windows
          path: stockfish-dev.exe
