name: Build Stockfish 18

on:
  push:
    branches: [main]
    tags:
      - 'v*'  # Khi tạo tag, nó sẽ tự động phát hành

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies (Linux/macOS)
        if: runner.os != 'Windows'
        run: sudo apt update && sudo apt install -y make g++ || brew install make g++

      - name: Install dependencies (Windows)
        if: runner.os == 'Windows'
        run: choco install mingw

      - name: Build Stockfish
        run: |
          cd src
          make -j$(nproc) build ARCH=x86-64-bmi2 || make -j$(nproc) build ARCH=x86-64-modern
        shell: bash

      - name: Rename binary
        run: |
          cd src
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            mv stockfish.exe stockfish-${{ runner.os }}.exe
          else
            mv stockfish
