name: Build Stockfish Dev on Windows

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'  # Build tự động mỗi ngày

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up MSVC compiler
        uses: ilammy/msvc-dev-cmd@v1

      - name: Install dependencies
        run: |
          choco install make mingw -y
        shell: powershell

      - name: Compile Stockfish
        run: |
          cd src
          make -j$(nproc) ARCH=x86-64-modern
          move stockfish.exe ..\stockfish-dev.exe
        shell: cmd

      - name: Upload compiled Stockfish binary
        uses: actions/upload-artifact@v4
        with:
          name: stockfish-dev-windows
          path: stockfish-dev.exe
          if-no-files-found: error
