name: Build Stockfish 18

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-2022
    strategy:
      matrix:
        arch: ["x86-64-bmi2", "x86-64-modern", "x86-64"]
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up pagefile
        uses: al-cheb/configure-pagefile-action@v1.4
        with:
          minimum-size: 16GB
          maximum-size: 16GB
          disk-root: "C:"
      
      - name: Build Stockfish
        run: |
          make clean
          make -j build ARCH=${{ matrix.arch }}
          strip stockfish.exe
      
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: stockfish-windows-${{ matrix.arch }}
          path: stockfish.exe
          if-no-files-found: error

  build-linux:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        arch: ["x86-64-bmi2", "x86-64-modern", "x86-64"]
    steps:
      - uses: actions/checkout@v4
      
      - name: Install dependencies
        run: sudo apt update && sudo apt install -y build-essential
      
      - name: Build Stockfish
        run: |
          make clean
          make -j build ARCH=${{ matrix.arch }}
          strip stockfish
      
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: stockfish-linux-${{ matrix.arch }}
          path: stockfish
          if-no-files-found: error

  build-macos:
    runs-on: macos-13
    strategy:
      matrix:
        arch: ["x86-64"]
    steps:
      - uses: actions/checkout@v4
      
      - name: Build Stockfish
        run: |
          make clean
          make -j build ARCH=${{ matrix.arch }}
          strip stockfish
      
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: stockfish-macos-${{ matrix.arch }}
          path: stockfish
          if-no-files-found: error
