name: Build Stockfish 18

on:
  push:
    branches: [main]
    tags:
      - 'v*'  # Khi tạo tag, nó sẽ tự động phát hành
  workflow_dispatch:  # Cho phép chạy thủ công
    inputs:
      os:
        description: "Chọn hệ điều hành để build"
        required: true
        default: "all"
        type: choice
        options:
          - all
          - ubuntu-latest
          - macos-latest
          - windows-latest

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ${{ fromJson(inputs.os == 'all' && '["ubuntu-latest", "macos-latest", "windows-latest"]' || format('["{0}"]', inputs.os)) }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies (Linux/macOS)
        if: runner.os != 'Windows'
        run: sudo apt update && sudo apt install -y make g++ || brew install make g++

      - name: Install dependencies (Windows)
        if: runner.os == 'Windows'
        run: choco install mingw

      - name: Build Stockfish
        run: |
          cd src
          make -j$(nproc) build ARCH=x86-64-bmi2 || make -j$(nproc) build ARCH=x86-64-modern
        shell: bash

      - name: Rename binary
        run: |
          cd src
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            mv stockfish.exe stockfish-${{ runner.os }}.exe
          else
            mv stockfish stockfish-${{ runner.os }}
          fi
        shell: bash

      - name: Archive binary
        run: |
          cd src
          zip -r stockfish-${{ runner.os }}.zip stockfish*
        shell: bash

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: stockfish-${{ runner.os }}
          path: src/stockfish-${{ runner.os }}.zip

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/*/*
          body: "Stockfish 18 binaries for Windows, Linux, and macOS."
          tag_name: ${{ github.ref_name }}
          draft: false
          prerelease: false
