name: Build Stockfish 18

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-2022
    strategy:
      matrix:
        arch: ["x86-64-bmi2", "x86-64-modern", "x86-64"]
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up pagefile
        uses: al-cheb/configure-pagefile-action@v1.4
        with:
          minimum-size: 16GB
          maximum-size: 16GB
          disk-root: "C:"
      
      - name: Build Stockfish
        run: |
          cd src
          make clean
          make -j ARCH=${{ matrix.arch }}
          strip stockfish.exe
      
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: stockfish-windows-${{ matrix.arch }}
          path: src/stockfish.exe
          if-no-files-found: error

      - name: Upload to GitHub Releases
        uses: softprops/action-gh-release@v1
        if: github.event_name == 'push'
        with:
          files: src/stockfish.exe
          tag_name: latest
          release_name: Stockfish Latest Release
          draft: false
          prerelease: false
